import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

interface SaleRow {
    fishName: string;
    weight: number;
    rate: number;
    amount: number;
}

interface Payment {
    amount?: number;
    amt?: number;
    date?: string;
    note?: string;
}

interface SlipData {
    boatName: string;
    agentName: string;
    date: string;
    sales: SaleRow[];
    commission: number;
    expAmts: Record<string, number>;
    totalDed: number;
    netPay: number;
    payments: Payment[];
    totalPaid: number;
    remaining: number;
    settled: boolean;
}

export const generateBoatSlipPDF = (data: SlipData, lang: 'en' | 'ta' = 'en') => {
    const doc = new jsPDF();
    const isTa = lang === 'ta';

    // Header
    doc.setFontSize(22);
    doc.setTextColor(8, 47, 73); // ocean-950
    doc.text(isTa ? 'மீன் சந்தை சீட்டு' : 'Fish Market Settlement', 14, 22);
    
    doc.setFontSize(10);
    doc.setTextColor(100, 116, 139); // ocean-500
    doc.text(isTa ? `தேதி: ${data.date}` : `Date: ${data.date}`, 14, 30);
    doc.text(isTa ? `முகவர்: ${data.agentName}` : `Agent: ${data.agentName}`, 14, 35);

    doc.setFontSize(16);
    doc.setTextColor(15, 23, 42);
    doc.text(data.boatName, 14, 45);
    doc.setLineWidth(0.5);
    doc.setDrawColor(224, 242, 254);
    doc.line(14, 48, 196, 48);

    // Sales Table
    const tableBody = data.sales.map((s, i) => [
        i + 1,
        s.fishName,
        `${s.weight} kg`,
        `Rs. ${s.rate}`,
        `Rs. ${s.amount.toLocaleString()}`
    ]);

    autoTable(doc, {
        startY: 55,
        head: [[isTa ? 'வ.எண்' : 'S.No', isTa ? 'மீன் பெயர்' : 'Fish Name', isTa ? 'எடை' : 'Weight', isTa ? 'விலை' : 'Rate', isTa ? 'தொகை' : 'Amount']],
        body: tableBody,
        theme: 'striped',
        headStyles: { fillColor: [14, 165, 233], textColor: 255 },
        styles: { fontSize: 10 },
    });

    const finalY = (doc as any).lastAutoTable.finalY + 10;

    // Financials
    doc.setFontSize(12);
    doc.setTextColor(15, 23, 42);
    doc.text(isTa ? 'நிதி விவரங்கள்' : 'Financial Details', 14, finalY);

    const grossSales = data.sales.reduce((sum, s) => sum + s.amount, 0);
    
    const financialRows = [
        [isTa ? 'மொத்த விற்பனை' : 'Gross Sales', `Rs. ${grossSales.toLocaleString()}`],
        [isTa ? 'கமிஷன்' : 'Commission', `- Rs. ${data.commission.toLocaleString()}`],
    ];

    Object.entries(data.expAmts).forEach(([k, v]) => {
        if (v > 0) {
            financialRows.push([k.replace('_', ' ').toUpperCase(), `- Rs. ${v.toLocaleString()}`]);
        }
    });

    financialRows.push([isTa ? 'மொத்த கழிவுகள்' : 'Total Deductions', `- Rs. ${data.totalDed.toLocaleString()}`]);
    financialRows.push([isTa ? 'நிகர தொகை' : 'Net Final Payable', `Rs. ${data.netPay.toLocaleString()}`]);

    autoTable(doc, {
        startY: finalY + 5,
        body: financialRows,
        theme: 'plain',
        styles: { fontSize: 10, cellPadding: 2 },
        columnStyles: { 0: { cellWidth: 100 }, 1: { halign: 'right', fontStyle: 'bold' } },
        didParseCell: (data) => {
            if (data.row.index === financialRows.length - 1) {
                data.cell.styles.textColor = [15, 118, 110]; // emerald-700
                data.cell.styles.fontSize = 12;
            }
        }
    });

    const finalY2 = (doc as any).lastAutoTable.finalY + 15;

    // Settlement Status
    doc.setFontSize(10);
    doc.setTextColor(100, 116, 139);
    doc.text(isTa ? 'தீர்வு நிலை:' : 'Settlement Status:', 14, finalY2);
    
    doc.setFontSize(14);
    doc.setTextColor(data.settled ? 16 : 180, data.settled ? 185 : 83, data.settled ? 129 : 9); // emerald-500 or amber-700
    doc.text(data.settled ? (isTa ? 'தீர்க்கப்பட்டது' : 'SETTLED') : (isTa ? 'நிலுவையில் உள்ளது' : 'PENDING'), 14, finalY2 + 8);

    if (!data.settled) {
        doc.setFontSize(10);
        doc.setTextColor(15, 23, 42);
        doc.text(isTa ? `மீதமுள்ள இருப்பு: Rs. ${data.remaining.toLocaleString()}` : `Remaining Balance: Rs. ${data.remaining.toLocaleString()}`, 14, finalY2 + 16);
    }

    // Footer
    doc.setFontSize(8);
    doc.setTextColor(148, 163, 184);
    doc.text('Generated by Fish Market Digital Ledger', 14, 285);

    doc.save(`FishMarket_Slip_${data.boatName}_${data.date}.pdf`);
};
