import { groupByFish as groupByFishUtil, FishRow } from '@/lib/fishUtils';
import { Badge as B, Label as L, Divider as D, fmt as F, dispDate as DD, toKey as TK, G as GT } from '@/components/ui/commonComponents';

export interface Payment {
    id: string | number;
    amount?: number;
    amt?: number;
    note?: string;
    date?: string;
    time?: string;
    by?: string;
}

export interface SaleRow {
    id: string | number;
    fishName?: string;
    fish?: string;
    weight: string | number;
    rate: string | number;
    buyer?: string;
    buyerName?: string;
    amountPaid?: number;
    balance?: number;
}

/* ── i18n specifically for the Agent Dashboard rewrite ───────────────────── */
export const T_AGENT = {
  en:{
    appName:"Fish Market Ledger", tagline:"Smart Digital Accounts for Fishing Agents",
    loginBtn:"Sign In", wrongCreds:"Invalid username or password.",
    demoAccounts:"Quick Login", logout:"Sign Out", langBtn:"தமிழ்", loadingApp:"Loading app...", loginFirst:"Please log in first.",
    roles:{agent:"Agent",boatOwner:"Boat Owner",admin:"Admin"},
    tabs:{entry:"Entry",slip:"Boat Slip",buyers:"Buyers",history:"History",reports:"Reports"},
    boats:{add:"Add Boat",delete:"Delete Boat",none:"No boats assigned to you yet. Click 'Add Boat' to get started.",namePlaceholder:"Sea King...",confirmDelete:'Delete boat "{name}"?', cancel:"Cancel"},
    actions:{addRow:"Add Row",addBuyer:"+ Buyer",save:"Save Slip",print:"Print",addBoat:"+ Boat",password:"Password",cancel:"Cancel",at:"@",saveShort:"SAVE",escShort:"ESC",newEntry:"New Entry",delete:"Delete",delSaleFail:"Failed to delete sale.",updSaleFail:"Failed to update sale.",delPayFail:"Failed to delete payment.",saving:"Saving..."},
    fields:{boat:"Boat",agent:"Agent",date:"Date",fish:"Fish Name",weight:"Weight (kg)",rate:"Rate (₹/kg)",amount:"Amount",buyer:"Buyer",total:"Total",paid:"Paid",remaining:"Remaining",unknownBoat:"Unknown Boat",unknownAgent:"Unknown Agent",unitKg:"kg",unitCurrency:"₹",buyerPlaceholder:"Buyer...",fishPlaceholder:"Fish...",avg:"avg"},
    voice:{btn:"Voice Entry",listening:"🔴 Listening… speak now",tip:'Say: "Thira 200 kilo rate 38" or "Rate 50 weight 10 Thira"',example:'"Thira 200 kilo rate 38"', fail:"❓ Couldn't parse", success:"✅ {n} actions processed", chromeOnly:"Please use Chrome for voice input.", examplesList:[{i:"🐟",t:"\"Thira 10 rate 50\""},{i:"🔄",t:"\"Rate 50 weight 10 Thira\""},{i:"💸",t:"\"Diesel 500\""},{i:"💾",t:"\"Save\" / \"Print\""},{i:"🗑️",t:"\"Undo\""}]},
    summary:{totalSales:"Total Sales",commission:"Commission",totalDed:"Total Deductions",netPayable:"Net Payable to Boat",paid:"Paid to Owner",remaining:"Remaining Balance",settled:"FULLY SETTLED",subTotal:"Sub Total",buyers:"buyers",noEntries:"No entries yet.",addHint:"Add a row above or use voice entry.",syncPending:"{n} entries waiting to sync",syncNow:"Sync Now ↗",offline:"Offline: Changes will be synced when back online"},
    expenses:{title:"Expenses & Deductions",diesel:"Diesel",ice:"Ice",salt:"Salt",van:"Van",netGear:"Fish Net / Gear",other:"Other",commPct:"Commission %",note:"Note"},
    payments:{title:"Payments to Boat Owner",amtPaid:"Amount Paid",notePlaceholder:"Cash / UPI / Cheque…",noteLbl:"Note",totalPaid:"Total Paid",by:"by",noPayments:"No payments recorded yet."},
    reports:{today:"Today",week:"This Week",totalSales:"Total Sales",totalDed:"Deductions",net:"Net Payable",boat:"Boat",noData:"No data for this period.",loading:"Loading reports...",boatWeeklyReport:"Boat Weekly Report",grossSales:"Gross Sales",netPayableOwner:"Net Payable to Owner",myTotalEarnings:"My Total Earnings",targetMet:"Target Met \u2705",downloadPDF:"Download PDF",sendToOwner:"Send to Owner",sendToAgent:"Send to Agent"},
    slip:{title:"Boat Owner's Slip",subtitle:"Fish Sale Settlement Slip",generatedBy:"Generated by",deductions:"Deductions",paymentsMade:"Payments Made",totalPaid:"Total Paid"},
    readOnly:"Read-only · Contact your agent to make changes.", srNo:"#",
    buyers:{
      title:"Buyer Management", searchPlaceholder:"Search buyers...", name:"Name", phone:"Phone", balance:"Balance", actions:"Actions", noBuyers:"No buyers found.", addBuyer:"Add Buyer", editBuyer:"Edit Buyer", namePlaceholder:"Enter name...",
      addBtn:"+ Buyer", totalBought:"Total Bought", totalPaid:"Total Paid", action:"Action", payBtn:"Pay", settled:"Settled", receiveCash:"Receive Cash", amtReceived:"Amount Received ({sym})", confirmPay:"Confirm Payment", addBuyerTitle:"Add New Buyer", buyerNameInput:"Buyer Name *", phoneInput:"Phone (Optional)", cancel:"Cancel",
      noPhone:"No phone", phonePlaceholder:"10-digit number", loadFail:"Failed to load buyers", addFail:"Failed to add buyer", payFail:"Failed to record payment", addFirst:"Add your first buyer using the button above.",
      waMsg: "👋 *Hello {name}*,\n\nThis is a reminder of your pending balance at the Fish Market.\n\n📊 *Total Bought: {sym}{total}*\n💵 *Total Paid: {sym}{paid}*\n🛑 *PENDING: {sym}{bal}*\n\nPlease settle the dues at the earliest.\n\nThank you!"
    },
    history:{
      title:"Sales History", searchPlaceholder:"Search by boat, buyer, or fish name...", loading:"Loading history...", noRecords:"No sales records found.", date:"Date & Time", boat:"Boat", buyer:"Buyer", fish:"Fish", qty:"Qty", amount:"Amount", status:"Status", actions:"Actions", paid:"PAID", credit:"CREDIT", billTitle:"*FISH BILL*", dateLbl:"Date", boatLbl:"Boat", fishLbl:"Fish", qtyLbl:"Qty", totalLbl:"Total", typeLbl:"Type", paidType:"Paid (Cash)", debtType:"Pending (Credit)", thankYou:"Thank you!"
    }
  },
  ta:{
    appName:"மீன் சந்தை கணக்கு", tagline:"மீன் முகவர்களுக்கான டிஜிட்டல் கணக்கு",
    loginBtn:"உள்நுழைக", wrongCreds:"தவறான பயனர் பெயர் அல்லது கடவுச்சொல்.",
    demoAccounts:"விரைவு உள்நுழைவு", logout:"வெளியேறு", langBtn:"English", loadingApp:"செயலி ஏற்றப்படுகிறது...", loginFirst:"தயவுசெய்து முதலில் உள்நுழையவும்.",
    roles:{agent:"முகவர்",boatOwner:"படகு உரிமையாளர்",admin:"நிர்வாகி"},
    tabs:{entry:"உள்ளீடு",slip:"படகு சீட்டு",buyers:"வாங்குபவர்கள்",history:"வரலாறு",reports:"அறிக்கை"},
    boats:{add:"படகு சேர்க்க",delete:"படகை நீக்கு",none:"உங்களுக்கு இன்னும் படகுகள் ஒதுக்கப்படவில்லை. தொடங்க 'படகு சேர்க்க' என்பதைக் கிளிக் செய்யவும்.",namePlaceholder:"கடல் ராஜா...",confirmDelete:'"{name}" படகை நீக்கவா?', cancel:"ரத்து"},
    actions:{addRow:"சேர்க்கவும்",addBuyer:"+ வாங்குபவர்",save:"சேமிக்கவும்",print:"அச்சிடு",addBoat:"படகு சேர்க்க",password:"கடவுச்சொல்",cancel:"ரத்து",at:"விலையில்",saveShort:"சேமி",escShort:"நீக்கு",newEntry:"புதிய உள்ளீடு",delete:"நீக்கு",delSaleFail:"விற்பனையை நீக்க முடியவில்லை.",updSaleFail:"விற்பனையை மாற்ற முடியவில்லை.",delPayFail:"பணத்தை நீக்க முடியவில்லை.",saving:"சேமிக்கப்படுகிறது..."},
    fields:{boat:"படகு",agent:"முகவர்",date:"தேதி",fish:"மீன் பெயர்",weight:"எடை (கிலோ)",rate:"விலை (₹/கிலோ)",amount:"தொகை",buyer:"வாங்குபவர்",total:"மொத்தம்",paid:"செலுத்தியது",remaining:"மீதி",unknownBoat:"தெரியாத படகு",unknownAgent:"தெரியாத முகவர்",unitKg:"கிலோ",unitCurrency:"₹",buyerPlaceholder:"வாங்குபவர்...",fishPlaceholder:"மீன்...",avg:"சராசரி"},
    voice:{btn:"குரல் உள்ளீடு",listening:"🔴 கேட்கிறது… பேசவும்",tip:'"திரா 200 கிலோ விலை 38" அல்லது "ரேட் 38 எடை 10 திரா" என சொல்லவும்',example:'"திரா 200 கிலோ விலை 38"', fail:"❓ புரியவில்லை", success:"✅ {n} செயல்கள் செய்யப்பட்டன", chromeOnly:"குரல் உள்ளீட்டிற்கு Chrome-ஐ பயன்படுத்தவும்.", examplesList:[{i:"🐟",t:"\"திரா 10 ரேட் 50\" / \"Thira 10 rate 50\""},{i:"🔄",t:"\"விலை 50 எடை 10 திரா\""},{i:"💸",t:"\"டீசல் 500\""},{i:"💾",t:"\"சேமி\" / \"அச்சிடு\""},{i:"🗑️",t:"\"Undo\""}]},
    summary:{totalSales:"மொத்த விற்பனை",commission:"கமிஷன்",totalDed:"மொத்த கழிவுகள்",netPayable:"படகு உரிமையாளருக்கு நிகர தொகை",paid:"கொடுத்தது",remaining:"மீதி தொகை",settled:"முழுமையாக தீர்க்கப்பட்டது",subTotal:"இடை மொத்தம்",buyers:"வாங்குபவர்கள்",noEntries:"பதிவுகள் இல்லை.",addHint:"மேலே ஒரு வரிசை சேர்க்கவும்.",syncPending:"{n} பதிவுகள் ஒத்திசைக்கப்படாமல் உள்ளன",syncNow:"இப்போது ஒத்திசை ↗",offline:"ஆஃப்லைன்: உங்கள் மாற்றங்கள் சேமிக்கப்படும்"},
    expenses:{title:"செலவுகள் & கழிவுகள்",diesel:"டீசல்",ice:"பனி",salt:"உப்பு",van:"வேன்",netGear:"மீன் வலை/உபகரணங்கள்",other:"மற்றவை",commPct:"கமிஷன் %",note:"குறிப்பு"},
    payments:{title:"படகு உரிமையாளருக்கு கொடுத்தது",amtPaid:"கொடுத்த தொகை",notePlaceholder:"ரொக்கம் / UPI / காசோலை…",noteLbl:"குறிப்பு",totalPaid:"மொத்தம் கொடுத்தது",by:"மூலம்",noPayments:"எந்த பணமும் பதிவு செய்யப்படவில்லை."},
    reports:{today:"இன்று",week:"இந்த வாரம்",totalSales:"மொத்த விற்பனை",totalDed:"கழிவுகள்",net:"நிகர தொகை",boat:"படகு",noData:"இந்த காலகட்டத்தில் தரவு இல்லை.",loading:"அறிக்கை ஏற்றப்படுகிறது...",boatWeeklyReport:"படகு வார அறிக்கை",grossSales:"மொத்த விற்பனை",netPayableOwner:"உரிமையாளருக்கு நிகர",myTotalEarnings:"என் மொத்த வருவாய்",targetMet:"இலக்கு அடைந்தது \u2705",downloadPDF:"PDF பதிவிறக்கம்",sendToOwner:"உரிமையாளருக்கு அனுப்பு",sendToAgent:"ஏஜெண்டிற்கு அனுப்பு"},
    slip:{title:"படகு உரிமையாளர் சீட்டு",subtitle:"மீன் விற்பனை தீர்வு சீட்டு",generatedBy:"தயாரித்தவர்",deductions:"கழிவுகள்",paymentsMade:"கொடுத்த தொகை விவரம்",totalPaid:"மொத்தம் கொடுத்தது"},
    readOnly:"படிக்க மட்டும் · மாற்றங்களுக்கு உங்கள் முகவரை தொடர்பு கொள்ளவும்.", srNo:"வ.எண்",
    buyers:{
      title:"வாங்குபவர் மேலாண்மை", searchPlaceholder:"வாங்குபவர்களைத் தேடுங்கள்...", name:"பெயர்", phone:"தொலைபேசி", balance:"மீதி", actions:"செயல்கள்", noBuyers:"வாங்குபவர்கள் யாரும் இல்லை.", addBuyer:"வாங்குபவர் சேர்க்க", editBuyer:"வாங்குபவர் விவரம் மாற்ற", namePlaceholder:"பெயரை உள்ளிடவும்...",
      addBtn:"+ வாங்குபவர்", totalBought:"மொத்த கொள்முதல்", totalPaid:"மொத்தம் செலுத்தியது", action:"செயல்", payBtn:"பணம்", settled:"தீர்க்கப்பட்டது", receiveCash:"பணம் பெறுதல்", amtReceived:"பெற்ற தொகை ({sym})", confirmPay:"உறுதிப்படுத்து", addBuyerTitle:"புதிய வாங்குபவரைச் சேர்க்க", buyerNameInput:"பெயர் *", phoneInput:"தொலைபேசி (விருப்பத்தேர்வு)", cancel:"ரத்து",
      noPhone:"தொலைபேசி இல்லை", phonePlaceholder:"10-இலக்க எண்", loadFail:"வாங்குபவர்களை ஏற்ற முடியவில்லை", addFail:"வாங்குபவரைச் சேர்க்க முடியவில்லை", payFail:"பணத்தைப் பதிவு செய்ய முடியவில்லை", addFirst:"மேலே உள்ள பொத்தானைப் பயன்படுத்தி முதல் வாங்குபவரைச் சேர்க்கவும்.",
      waMsg: "👋 *வணக்கம் {name}*,\n\nமீன் சந்தையில் உங்கள் நிலுவைத் தொகை பற்றிய நினைவூட்டல் இது.\n\n📊 *மொத்த கொள்முதல்: {sym}{total}*\n💵 *செலுத்தியது: {sym}{paid}*\n🛑 *நிலுவை: {sym}{bal}*\n\nதயவுசெய்து நிலுவைத் தொகையை விரைவில் செலுத்துங்கள்.\n\nநன்றி!"
    },
    history:{
      title:"விற்பனை வரலாறு", searchPlaceholder:"படகு, வாங்குபவர் அல்லது மீன் பெயரைத் தேடுங்கள்...", loading:"வரலாறு ஏற்றப்படுகிறது...", noRecords:"விற்பனை பதிவுகள் எதுவும் இல்லை.", date:"தேதி & நேரம்", boat:"படகு", buyer:"வாங்குபவர்", fish:"மீன்", qty:"அளவு", amount:"தொகை", status:"நிலை", actions:"செயல்கள்", paid:"கொடுத்தது", credit:"நிலுவை", billTitle:"*மீன் பில்*", dateLbl:"தேதி", boatLbl:"படகு", fishLbl:"மீன்", qtyLbl:"அளவு", totalLbl:"மொத்தம்", typeLbl:"வகை", paidType:"கொடுத்தது (ரொக்கம்)", debtType:"நிலுவை (கடன்)", thankYou:"நன்றி!"
    }
  },
};

/* ── Static data ─────────────────────────────────── */
export const FISH_EN=["Thira","Malavai","P.Ula","Iral","Kavala","Vanjaram","Seela","Nethili","Mathi","Pomfret","Shark","Kori","Viral","Katla","Ayala","Sankara","Vela","Kiluvai","Parai","Soodai","Nandu","Kanankeluthi"];
export const FISH_TA=["திரா","மலவை","P.உலா","இறால்","கவலா","வஞ்சிரம்","சீலா","நெத்திலி","மத்தி","ஆவோலி","சுறா","கோரி","விரால்","கட்லா","அயலா","சங்கரா","வேலா","கிளுவை","பாறை","சூடை","நண்டு","கானாங்கெளுத்தி"];
export const FISH_TA_SYNONYMS: Record<string, string[]> = {
    "திரா": ["த்ரா", "திர", "திரா"],
    "மலவை": ["மலைவை", "மலவை"],
    "இறால்": ["இறால்", "இரால்", "ஈரால்"],
    "கவலா": ["கவளா", "கவலா"],
    "வஞ்சிரம்": ["வஞ்சரம்", "வஞ்சிரம்", "Neimeen"],
    "சீலா": ["ஷீலா", "சீலா"],
    "நெத்திலி": ["நெத்தலி", "நெத்திலி"],
    "மத்தி": ["மட்டி", "மத்தி"],
    "ஆவோலி": ["ஆவொலி", "வொலி", "ஆவோலி"],
    "சுறா": ["சூறா", "சுறா"],
    "கோரி": ["கோறி", "கோரி"],
    "விரால்": ["விறால்", "விரால்"],
    "சங்கரா": ["சங்கறா", "சங்கரா"],
    "அயலா": ["அயிலா", "அயலா"],
	"பாறை": ["பரை", "பாறை"],
	"சூடை": ["சூட", "சூடை"],
	"நண்டு": ["நன்டு", "நண்டு"],
	"கானாங்கெளுத்தி": ["கானாங்கெளுத்தி", "கானான்", "அயிலா"]
};
export const EXP_KEYS=["diesel","ice","salt","van","netGear","other"] as const;
export const EXP_ICONS: Record<string, string>={diesel:"⛽",ice:"🧊",salt:"🧂",van:"🚐",netGear:"🕸️",other:"📦"};
export const FISH_COLORS=["#6366F1","#0891B2","#059669","#D97706","#DC2626","#7C3AED","#0D9488","#C2410C","#1D4ED8","#15803D"];
export const ROLE_COLORS: Record<string, string>={agent:"#6366F1",boatOwner:"#059669",admin:"#D97706"};

/* ── Helpers ─────────────────────────────────────── */
export const fmt     = F;
export const toKey   = TK;
export const dispDate= DD;
export const weekKeys= () => Array.from({length:7},(_,i)=>{const d=new Date();d.setDate(d.getDate()-i);return TK(d);});
let _id=Date.now(); 
export const uid=()=>++_id;

export const groupByFish = (rows: SaleRow[]) => {
    return groupByFishUtil(rows as unknown as FishRow[]) as unknown as Record<string, SaleRow[]>;
};

/* ── Design tokens ───────────────────────────────── */
export const G = { ...GT, coral400: "#E11D48" };

/* ── Tiny shared UI ──────────────────────────────── */
export const Label = L;
export const Badge = B;
export const Divider = D;

export const GCard = ({ children, style, onClick, className }: { children: React.ReactNode, style?: React.CSSProperties, onClick?: () => void, className?: string }) => (
  <div onClick={onClick} style={style} className={`bg-white border rounded-lg p-6 ${className || ''}`}>
    {children}
  </div>
);

export const makeInp = (): React.CSSProperties => ({ border:`1px solid ${G.text}`,borderRadius:2,padding:"10px 14px",fontSize:14,color:G.text,background:G.inputBg,outline:"none",width:"100%",fontFamily:"inherit",height:"42px" });

export const TH: React.CSSProperties = {padding:"12px 16px",fontWeight:700,color:G.text,fontSize:11,letterSpacing:0.8,background:G.card,borderBottom:`1px solid ${G.text}`,borderTop:`1px solid ${G.text}`,textTransform:"uppercase",textAlign:"left"};
export const TD: React.CSSProperties = {padding:"12px 16px",fontSize:14,borderBottom:`1px solid ${G.border}`,color:G.text,textAlign:"left"};
